name: Android CI

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Create Release and Upload APK
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/**/*.apk
        name: Release ${{ github.event.release.tag_name }}
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
